name: Mirror rolling to rolling-devel

on:
  push:
    branches: [ rolling ]

jobs:
  mirror-to-rolling-devel:
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1
      with:
        target-branch: rolling-devel
